java_library(
    name = "greeter",
    srcs = ["Greeter.java"],
    visibility = ["//visibility:public"],
)

# Export the source file so it can be referenced from parent package
exports_files(["Greeter.java"], visibility = ["//visibility:public"])

